# specify the version for docker-compose.yml
version: "3.8"

# add the services needed
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    # build the Dockerfile, alternatively use an image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    depends_on:
      - "postgres"
    env_file:
      - .env
volumes:
  dbdata: # create the volume for persisting data